from __future__ import annotations

from dataclasses import dataclass
from typing import Generic, Protocol, TypeVar

from ..ds_types import CompareFunc, FreeFunc, VisitFunc

T = TypeVar("T")


@dataclass(frozen=True)
class Config(Generic[T]):
    initial_capacity: int = 0
    free_value: FreeFunc[T] | None = None


class Array(Protocol[T]):
    def size(self) -> int: ...
    def capacity(self) -> int: ...
    def is_empty(self) -> bool: ...

    def reserve(self, min_capacity: int) -> bool: ...
    def shrink_to_fit(self) -> bool: ...
    def clear(self) -> None: ...

    def get(self, index: int) -> tuple[T, bool]: ...
    def set(self, index: int, value: T) -> bool: ...

    def push(self, value: T) -> bool: ...
    def pop(self) -> tuple[T, bool]: ...
    def insert(self, index: int, value: T) -> bool: ...
    def remove(self, index: int) -> tuple[T, bool]: ...

    def index_of(self, value: T, compare: CompareFunc[T]) -> int: ...
    def for_each(self, visit: VisitFunc[T]) -> None: ...
