from __future__ import annotations

from dataclasses import dataclass
from typing import Generic, Protocol, TypeVar

from ..ds_types import FreeFunc, KVVisitFunc

V = TypeVar("V")


@dataclass(frozen=True)
class Config(Generic[V]):
    free_value: FreeFunc[V] | None = None


class Trie(Protocol[V]):
    def size(self) -> int: ...
    def is_empty(self) -> bool: ...

    def insert(self, key: str, value: V) -> bool: ...
    def get(self, key: str) -> tuple[V, bool]: ...
    def contains(self, key: str) -> bool: ...
    def remove(self, key: str) -> tuple[V, bool]: ...

    def has_prefix(self, prefix: str) -> bool: ...
    def prefix_count(self, prefix: str) -> int: ...
    def for_each_prefix(self, prefix: str, visit: KVVisitFunc[str, V]) -> None: ...

    def clear(self) -> None: ...
