from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Generic, Protocol, TypeVar

from ..ds_types import CompareFunc, FreeFunc, HashFunc, KVVisitFunc

ID = TypeVar("ID")
VertexValue = TypeVar("VertexValue")
EdgeValue = TypeVar("EdgeValue")


class Kind(Enum):
    DIRECTED = 0
    UNDIRECTED = 1


@dataclass(frozen=True)
class Config(Generic[ID, VertexValue, EdgeValue]):
    kind: Kind
    hash_vertex_id: HashFunc[ID]
    compare_vertex_id: CompareFunc[ID]
    free_vertex_id: FreeFunc[ID] | None = None
    free_vertex_value: FreeFunc[VertexValue] | None = None
    free_edge_value: FreeFunc[EdgeValue] | None = None


class Graph(Protocol[ID, VertexValue, EdgeValue]):
    def vertex_count(self) -> int: ...
    def edge_count(self) -> int: ...
    def is_directed(self) -> bool: ...

    def add_vertex(self, vertex_id: ID, value: VertexValue) -> bool: ...
    def set_vertex(self, vertex_id: ID, value: VertexValue) -> tuple[VertexValue, bool]: ...
    def get_vertex(self, vertex_id: ID) -> tuple[VertexValue, bool]: ...
    def remove_vertex(self, vertex_id: ID) -> tuple[ID, VertexValue, bool]: ...

    def add_edge(self, from_id: ID, to_id: ID, value: EdgeValue) -> bool: ...
    def get_edge(self, from_id: ID, to_id: ID) -> tuple[EdgeValue, bool]: ...
    def has_edge(self, from_id: ID, to_id: ID) -> bool: ...
    def remove_edge(self, from_id: ID, to_id: ID) -> tuple[EdgeValue, bool]: ...

    def out_degree(self, vertex_id: ID) -> int: ...
    def in_degree(self, vertex_id: ID) -> int: ...

    def for_each_vertex(self, visit: KVVisitFunc[ID, VertexValue]) -> None: ...
    def for_each_neighbor(self, vertex_id: ID, visit: KVVisitFunc[ID, EdgeValue]) -> None: ...
