from __future__ import annotations

from dataclasses import dataclass
from typing import Generic, Protocol, TypeVar

from ..ds_types import CompareFunc, FreeFunc, VisitFunc

T = TypeVar("T")


@dataclass(frozen=True)
class Config(Generic[T]):
    free_value: FreeFunc[T] | None = None


class LinkedList(Protocol[T]):
    def size(self) -> int: ...
    def is_empty(self) -> bool: ...

    def push_front(self, value: T) -> bool: ...
    def push_back(self, value: T) -> bool: ...
    def pop_front(self) -> tuple[T, bool]: ...
    def pop_back(self) -> tuple[T, bool]: ...

    def front(self) -> tuple[T, bool]: ...
    def back(self) -> tuple[T, bool]: ...
    def get(self, index: int) -> tuple[T, bool]: ...
    def insert(self, index: int, value: T) -> bool: ...
    def remove_at(self, index: int) -> tuple[T, bool]: ...
    def remove_value(self, value: T, compare: CompareFunc[T]) -> tuple[T, bool]: ...

    def reverse(self) -> None: ...
    def clear(self) -> None: ...
    def for_each(self, visit: VisitFunc[T]) -> None: ...
